"""empty message

Revision ID: 367d8ccc230f
Revises: e2c86ad35888
Create Date: 2021-05-15 13:10:30.835731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367d8ccc230f'
down_revision = 'e2c86ad35888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('img', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=800), nullable=True),
    sa.Column('url', sa.String(length=800), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_product',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'product_id')
    )
    op.add_column('user', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('photo_url', sa.String(length=200), nullable=False))
    op.create_foreign_key(None, 'user', 'product', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'photo_url')
    op.drop_column('user', 'customer_id')
    op.drop_table('user_product')
    op.drop_table('product')
    # ### end Alembic commands ###
