"""empty message

Revision ID: 75b2589e01ba
Revises: 6a987c737280
Create Date: 2021-05-20 18:26:31.194970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b2589e01ba'
down_revision = '6a987c737280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('variants', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'variants')
    # ### end Alembic commands ###
