"""empty message

Revision ID: 7e3a17d6e34d
Revises: 367d8ccc230f
Create Date: 2021-05-15 13:23:11.723589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3a17d6e34d'
down_revision = '367d8ccc230f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_customer_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_customer_id_fkey', 'user', 'product', ['customer_id'], ['id'])
    # ### end Alembic commands ###
