import React, { useContext } from "react";
import { Context } from "../store/appContext";

import Form from "react-bootstrap/Form";
import Card from "react-bootstrap/Card";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import Button from "react-bootstrap/Button";
import Container from "react-bootstrap/Container";
import "../../styles/create-sign_in_account.scss";

export const Register = () => {
	const { store, actions } = useContext(Context);

	return (
		<Container className="my-2">
			<h5 className="create-account-title text-center pt-2">PRIVACY POLICY</h5>
			<Row className="mx-auto pt-4">
				<Col sm={12} md={6} lg={4} className="mx-auto">					

                       <p>Cutie Pie, LLC (“we,”“us,” or “our”) is pleased to provide you with access to our Website. This Privacy Policy describes our practices with respect to the collection, transfer, manipulation, disclosure and other uses of Your Information and certain other information collected by us through our Website. For purposes of this Privacy Policy, “Your Information” means information about you which may be of a confidential nature and may include personally identifiable information, including your first and last name and email address.</p>

                        <p>This Privacy Policy applies to information collected by us through our Website, but does not apply to information collected by any person or entity other than us, even if related to our Website (such as a third-party website, content, application or platform that may link to or be accessible from or on our Website, such as the PayCom platform). 
                        PLEASE READ THIS PRIVACY POLICY CAREFULLY BEFORE USING OUR WEBSITE. BY USING OUR WEBSITE, OR BY CLICKING TO ACCEPT OR AGREE TO OUR TERMS OF USE WHEN THIS OPTION IS MADE AVAILABLE TO YOU, YOU ACCEPT AND AGREE TO BE BOUND AND ABIDE BY OUR TERMS OF USE, INCLUDING THIS PRIVACY POLICY. IF YOU DO NOT WANT YOUR INFORMATION USED OR DISCLOSED IN THE MANNER DESCRIBED IN THIS PRIVACY POLICY, OR IF YOU DO NOT AGREE WITH ANY TERM OR CONDITION IN THIS PRIVACY POLICY OR OUR TERMS OF USE, THEN YOU MUST NOT ACCESS OR USE OUR WEBSITE OR SUBMIT YOUR INFORMATION TO US.
                        This Privacy Policy may change from time to time (see Section 8, “Changes to our Privacy Policy”). Your continued use of our Website after we make changes is deemed to be acceptance of those changes, so please check this policy periodically for updates.</p>
                        
                        <p>1. Children Under the Age of 18</p>

                        <p>Our Website is intended to be accessed and used only by adults and are not directed to minors. If you are below the age of 18, you may access and participate in our Website only under the supervision of a parent or legal guardian who agrees to be bound by this Privacy Policy and our Terms of Use.</p> 

                        <p>We do not knowingly collect personally identifiable information by anyone under the age of 16 and you should not provide us with any information regarding any individual under the age of 16. If we learn that we have inadvertently gathered information from anyone under the age of 16, we will take reasonable measures to promptly remove that information from our records.</p>

                        <p>California residents under 16 years of age may have additional rights regarding the collection and sale of their personal information. Please see Section 10, “Your California Privacy Rights” for more information.
                        2. What Information We Collect and How We Collect It

                        We receive and collect several types of information about you, such as the information described below.

                        Information you provide to us: From time to time, you may provide us with certain information, including Your Information or information of third parties, such as the company on whose behalf you are making an inquiry. Instances where you may provide this information include when you request us to contact you or request a quote for our products or services through our Website, fill out forms or fields on or through our Website, or sign up for any promotions or to receive newsletters or other materials about us, our Website or those of third parties. By way of example, when you request us to contact you or provide a quote for our products or services, you may provide your first and last name, email, phone number and the reason for your inquiry. 

                        Information we receive from third parties:  We may obtain information about you from sources other than you, such as from PayCom, which is our provider of certain human resource-related services, and through which you may apply for a job position with us. Any content or information submitted by you via the PayCom platform (including your resume and/or other application detail) will be used and disclosed by PayCom in accordance with PayCom’s privacy policy, which is currently located at: https://paycom.com/privacy/ .

                        We may also obtain information about you from social media networks on or through which you may access the Website. The information that we will receive depends on the third party and your privacy settings with that third party. All information that you disclose to third parties will be subject to the privacy policies and practices of such third parties. You should review the privacy policies and practices of such third parties prior to disclosing information to them.

                        We may also collect information on or from third party platforms such as DirectMail2.0, HubSpot, Google AdWords, Google Analytics, etc. 

                        Information we collect through automatic data collection technologies: We and third parties acting on our behalf (such as DirectMail2.0) may use various technologies to collect and store information when you use our Website, including sending cookies, web beacons, pixel tags or other anonymous identifiers to your device, or otherwise tracking your activities on our Website over time. “Cookies” are pieces of data stored on a computer, mobile phone or other device. A “web beacon” is a type of technology that lets us know if you visited a certain page or whether you opened an email. A “pixel tag” is a type of technology placed within a website or e-mail for the purpose of tracking activity, which is often used in combination with cookies. Other “anonymous identifiers” include random strings of characters used for the same purposes as cookies, such as with mobile devices where cookie technology may not be available. These technologies help us know that you are logged on to or using our Website, provide you with features based on your preferences, help us understand when and how you are interacting with our Website and compile other information regarding your use of our Website. We also may use these technologies to collect information about your online activities over time and/or across third-party websites or other online Website (a practice known as behavioral tracking). 

                        The information collected through these technologies, standing alone, cannot be used to determine your identity. Such information may, however, be combined in a way that makes it become personally identifiable information (i.e., information that can identify you). For example, we may tie this information to personal information about you that we collect from other sources or that you provide to us. If this happens, we will treat the combined information as personally identifiable information.

                        It may be possible to disable some (but not all) Cookies or automatic data collection technologies through your device or browser settings, but doing so may affect the functionality of our Website. The method for disabling Cookies or other automatic collection technologies may vary by device and browser, but can usually be found in preferences or security settings. For example, iOS and Android devices each have settings which are designed to limit forms of ad tracking. 
                        To make a do-not-track request with respect to behavioral tracking on our Website or to receive information on how we respond to web browser signals and other mechanisms that enable consumers to exercise choice about behavioral tracking, please contact us at privacy@cutiepie.com or in writing at:
                        
                        Attn: Privacy Request
                        Cutie Pie
                        XXX Street
                        XXX, FL 33010
                        
                        In contacting us, you must include the reference to our “Privacy Request” on the subject line and in the body of the message and include the email or physical address for us to send our response. We reserve the right not to respond to inquiries submitted other than to the address specified above.
                        Our Collection Practices with Respect to Certain Specific Information:
                        General Use and Preference Information. We may collect, receive and store information regarding your general use of our Website (such as details of how and when you used our Website, interactions with our Website, login information, resources that you access, your Internet protocol address, your browser type and your device type), as well as your preferences. 

                        Device Information. When you access or use our Website through your computer, mobile phone or other device, we may collect information regarding and related to your device, such as hardware models and IDs, device type, operating system version, the request type, the content of your request and basic usage information about your use of our Website, such as date and time. In addition, we may collect information regarding application-level events, such as crashes, and associate that temporarily with your account (if any) to provide customer service. We may also collect and store information locally on your device using mechanisms such as browser web storage and application data caches.

                        Location Information. If you submit your zip code or other geographic information to us, you may provide us with your location information. Furthermore, if you enable the collection of location information on your device, then we may collect information about your actual location, such as your mobile device’s GPS coordinates. We may also use other technologies to determine your location (such as through the location of nearby Wifi access points or cell towers), or obtain your location information from third parties. 
                        Third-party content providers may collect information: Some content or applications, including advertisements, on our Website may be served by third parties, including PayCom, advertisers, ad networks and servers, content providers and application providers. These third parties may collect information about you when you use our Website using cookies alone or in conjunction with web beacons or other tracking technologies. We do not control these third parties' tracking technologies or how they may be used. If you have any questions about an advertisement or other targeted content, you should contact the responsible provider directly. Please note that the information collected by these third parties may be associated with Your Information and that these third parties may collect information, including Your Information, about your online activities over time and across different websites and other online services. 
                        3. How We Use Your Information

                        We may use the information we collect for various lawful business purposes. Among others, these purposes may include using this information, including Your Information, to:
                        •	Present our Website, product or services, and related content to you. For example, if you provide us with your contact information for purposes of requesting that we contact you or that we provide you with a quote, or for receiving emails, promotional materials or other information or content from us, we will use the information you provide us to contact you, provide you with a quote, and to send you such information or materials. Additionally, we may use Your Information to administer surveys, giveaways, or other promotional activities.
                        •	Contact you and provide you with information. For example, we might contact you via e-mail or other communications to provide you with Website or service offering updates, promotions, offers, personalized information and other information from us or our third-party service providers or business partners or to respond to comments, inquiries, job applications, and other information submitted by you.
                        •	Provide you with customer support. For example, if you request us to contact you in connection with any customer support matters, we may collect certain information from you in order to assist you as requested. 
                        •	Analyze, improve and manage our Website, products, service offerings and operations. For example, we might obtain feedback regarding our Website, products, and service offerings, understand and anticipate your needs and preferences, better understand your use of our Website or products or service offerings, customize and tailor Website content and advertising, improve our marketing and promotional efforts, engage in statistical analysis and provide feedback or information to our business partners, vendors, advertisers and other third parties, including PayCom. 
                        •	Resolve problems and disputes, and engage in other legal and security matters. For example, we may use the information we collect to comply with, monitor compliance with and enforce this Privacy Policy, our Terms of Use (including any terms and conditions incorporated or referenced in our Terms of Use) and any other applicable agreements and policies, meet other legal and regulatory requirements, and protect the security and integrity of our Website. We might also use information that we collect to investigate any compliant you make regarding our Website, content, products, service offerings or other related matters, to provide evidence in any dispute or anticipated dispute between you and us, or to prevent fraud or other criminal or otherwise inappropriate activities.
                        •	Display advertisements to our advertisers' target audiences. For example, we may use your device information for direct advertising and retargeting ads, such as providing you with information or advertising relating to our products or services based on your precise geolocation, when in line with the preferences you have shared with us. Additionally, even though we do not disclose your personal information for these purposes without your consent, if you click on or otherwise interact with an advertisement, the advertiser may assume that you meet its target criteria. Note also that our third party content providers may use information they collect via our Website to provide you with interest-based (aka behavioral) advertising or other targeted content.
                        •	Comply with a request from you in connection with the exercise of your rights. For example, where you have asked us not to contact you for marketing purposes, we or our service providers will keep a record of this on our suppression lists to be able to comply with your request.
                        •	Other Purposes. We may also use your information in other ways. To the extent required by applicable law, we will provide notice at the time of collection and obtain your consent.
                        4. How We Disclose Your Information

                        General Disclosure of Your Information:  We may disclose the information we collect, including Your Information:
                        •	to our third-party vendors or suppliers (including PayCom) so that they may provide support for our internal and business operations, including for the handling of job applications, data processing, data verification, data storage, surveys, research, internal marketing, delivery of promotional, marketing and transaction materials and our Website’s maintenance and security. For example, we use (and thus disclose certain of Your Information to):
                        o	PayCom so that you may apply for one or more of our job listings posted on the PayCom platform and served on our Website. PayCom’s privacy policy is currently located at: https://paycom.com/privacy/ .
                        o	DirectMail2.0 in order to effectively market our products or services to you – you can read more about how DirectMail2.0 uses Your Information by visiting the DirectMail2.0 website (located here: https://directmail2.com/) and downloading their Privacy Policy, currently available under the “About Us” tab.
                        o	Google Analytics so that they can help us understand how our customers use the Website – you can read more about how Google uses Your Information here: https://www.google.com/intl/en/policies/privacy/. You can also opt-out of Google Analytics here: https://tools.google.com/dlpage/gaoptout.
                        o	HubSpot in order to effectuate our marketing campaigns — you can read more about how HubSpot and JustUno use Your Information here: https://legal.hubspot.com/privacy-policy and https://www.justuno.legal/privacy-policy.html .
                        o	MailChimp in order to administer surveys regarding our products and services – you can read more about how MailChimp uses Your Information here: https://mailchimp.com/legal/privacy/ .
                        •	to our affiliates and their respective employees, agents and representatives involved in delivering our Website, products and other services to you. For example, we use (and thus disclose certain of Your Information to) Google Firebase when you access our Website through our mobile app. Google Firebase usage is subject to Google’s Privacy Policy (link provided above). 
                        •	to fulfill the purpose for which you provide it;
                        •	to any person who, in our reasonable judgment, is authorized to receive Your Information as your agent, including as a result of your business dealings with that person (for example, your attorney);
                        •	to third parties when you engage in certain activities through our Website that are sponsored by such third parties, such as purchasing products or services offered by a third party, electing to receive information or communications from a third party or electing to participate in contests, sweepstakes, games or other programs sponsored, in whole or in part, by a third party;
                        •	to third parties that are interested in contacting you or providing offers to you that may be related to our Website or to products or services you may find of interest;
                        •	as required by applicable law or ordered by a court, regulatory or administrative agency;
                        •	as we deem necessary, in our sole discretion, if we believe that you are violating any applicable law, rule, restriction or regulation, or are otherwise interfering with another’s rights or property, including our rights or property;
                        •	if requested by authorities in the event of any act instance of local, regional or national emergency;
                        •	to enforce our Terms of Use, including this Privacy Policy, and any other applicable agreements and policies;
                        •	with your consent;
                        •	to otherwise enforce or protect our rights; and
                        •	in connection with a Business Transfer (see “Other Disclosures by Us” below).
                        Please note that the list above is not exhaustive and that we may, to the extent permitted by applicable law, disclose the information we collect to third parties at any time, for any lawful purpose, without notice or compensation to you. 

                        When we disclose the information we collect to third parties, such information will become permanently subject to the information use and sharing practices of the third party, and the third party will not be restricted by this Privacy Policy with respect to its use and further sharing of such information. Furthermore, these third parties may further disclose, share and use this information. By submitting information (including Your Information) to us, you expressly consent to such disclosure and use of such information. If you do not want this information (including Your Information) shared as described above, then you should not provide us with such information. 
                        Other Disclosures by Us:

                        Aggregation and Depersonalization. We may use and disclose any de-identified information for any lawful purpose, including for any commercial purpose. De-identified Information means information that does not identify you, including any identifiable information de-identified by either by combining it with information about others, for example, by aggregating your information with information about other persons, or by removing characteristics, such as your name, that make the information personally identifiable to you.

                        Business Transfers. We may disclose, lease, sell, assign or transfer the information we collect (including Your Information) to third parties in connection with a Business Transfer. A “Business Transfer” means a sale, acquisition, merger, consolidation, reorganization, bankruptcy or other corporate change involving us, even if the Business Transfer is only being contemplated and regardless of whether the Business Transfer relates to a part of or our whole business. Nothing in this Privacy Policy is intended to interfere with our ability to transfer all or part of our business, equity or assets (including our Website) to an affiliate or independent third party at any time, for any lawful purpose, without notice or compensation to you.
                        Circumvention of Security Measures: We use a certain technical, administrative and organizational security measures to keep Your Information safe. However, despite our efforts, please be aware that methods of transmission and electronic storage are not completely secure. We cannot guarantee the privacy or security of Your Information, as third parties may unlawfully intercept or access transmissions or electronic storage. Further, to the extent permitted by law, we are not responsible for circumvention of any privacy settings or security measures of our Website. Therefore, you use our Website at your own risk, you should not expect that Your Information will always remain private, and we do not guarantee the performance or adequacy of our security measures. In the event that an unauthorized third party compromises our security measures, to the extent permitted by law, we will not be responsible for any damages, directly or indirectly, caused by an unauthorized third party’s ability to view, use or disseminate Your Information.
                        5. Choices About How We Use and Disclose Your Information

                        We strive to provide you with choices regarding our collection, use and disclosure of the information that we collect. Below are some mechanisms that provide you with control over such collection, use or disclosure:
                        •	Cookies. If you do not wish us to collect cookies, you may set your browser to refuse cookies, or to alert you when cookies are being sent. If you do so, please note that some or all parts of our Website may then be inaccessible or may not function properly.
                        •	Email Offers. If you do not wish to receive email offers or other information or communications from us, you can opt-out of receiving such email offers or other information or communications from us (other than e-mails or other information or communications related to the status of your job application with us (if any), correction of user data, change of password and other similar communications essential to your transactions on or through our Website) by using the unsubscribe process at the bottom of the e-mail. Please be aware that it can take up to 10 business days to remove you from our marketing email lists. If you opt-out from receiving our marketing emails, you may continue to receive certain status emails relating to your transactions on or through our Website. 
                        •	Managing Your Information. If a portion of our Website allows you to create an account with us, then you can review and update Your Information by logging into that portion of our Website, visiting your account profile page and making changes.
                        •	Online Behavioral Advertising. As described above, we may use Your Information to provide you with targeted advertisements or marketing communications we believe may be of interest to you. Certain third-party advertising networks that deliver behavioral advertising are members of the Network Advertising Initiative (“NAI”). You can prevent NAI member companies from collecting preference data about you by visiting http://www.networkadvertising.org/choices/ and following the NAI’s directions. Note that if you opt-out through the NAI, you will still receive advertising. In addition, if you opt-out through the NAI and later delete your cookies, use a different browser or buy a new computer, you will need to renew your opt-out choice. Additional options for opting out of target advertising include, without limitation:
                        o	FACEBOOK - https://www.facebook.com/settings/?tab=ads
                        o	TWITTER - https://help.twitter.com/en/safety-and-security/privacy-controls-for-tailored-ads
                        o	GOOGLE - https://www.google.com/settings/ads/anonymous
                        o	BING - https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads 
                        o	Digital Advertising Alliance - http://optout.aboutads.info/
                        In addition to the above, you may also opt-out of your information being used by our third-party lead-matching service provider, DirectMail2.0 by visiting DirectMail2.0’s collection pixel provider’s instructions for doing so. Information on DirectMail2.0’s pixel provider is available in the DirectMail2.0 privacy policy, which available is available for download under the “About Us” tab on the DirectMail2.0 website (located here: https://directmail2.com/). As of the last update to this Privacy Policy, DirectMail2.0’s current pixel provider for its lead-matching services was Claritas, and you can opt-out of Claritas’ use of your information by visiting: https://claritas.com/privacy-legal/#opt-out 
                        California residents may have additional personal information rights and choices. Please see Section 10, “Your California Privacy Rights” for more information.
                        6. Information that You Disclose to Third Parties

                        Our Website, including any of our newsletters or e-mail messages, may contain links or access to websites or platforms operated by third parties that are beyond our control, including PayCom. Links or access to third parties from our Website is not an endorsement by us of such third parties, or their respective websites, applications, products, platforms or practices. We are not responsible for the privacy policies, terms and conditions, practices or the content of such third parties. All information that you disclose to such third parties will be subject to the privacy policies and practices of such third parties. You should review the privacy policies and practices of such third parties prior to disclosing information to them. If you have any questions about how these third parties use your information, you should review their policies and contact them directly.
                        7. Operation of our Website in the United States

                        Our Website is operated in the United States. As a result, the information we collect (including Your Information) will be used and disclosed as described in this Privacy Policy in the United States, as well as in other countries if you access our Website outside of the United States. In some cases, the laws of countries other than the United States regarding our use and disclosure of your information may be less stringent than the laws of the United States. 
                        8. Changes to Our Privacy Policy

                        We may amend this Privacy Policy at any time and from time to time. Amendments will take effect immediately upon us posting the updated Privacy Policy on the Website. Accordingly, you are encouraged to revisit this Privacy Policy from time to time in order to review any changes that we have made. The date on which this Privacy Policy was last updated will be noted immediately above this Privacy Policy.
                        9. Contacting Us                    
            



				</Col>
				<Col sm={12} className="mx-auto">
					<img
						className="img-fluid"
						src="https://res.cloudinary.com/scormier/image/upload/v1620161769/cutie-pie/buttlerfly-path_aycx2b.png"
						alt="butterfly"
						w-100
					/>
				</Col>
			</Row>
		</Container>
	);
};
